name: Testing Secret Variables
  run: 
    test_context_variables() {
      echo "This is a test"
    }
 test_context_variables
on:
  workflow_dispatch
env:
      ACTIONS_STEP_DEBUG: true
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Secret Variable"
        run: |
          echo "Secret Value : ${{ secrets.MY_KEY }}"
          ${{ secrets.MY_KEY }}
